---
- hosts: all
  tasks:
   - name: fetch file
     fetch: src=/home/tim/sshkeys/sshkeytim.pub dest=buffer/ flat=yes
     when: "{{ inventory_hostname == '192.168.6.145' }}"
    
    - name: copy file
      copy: src=buffer/sshkeytim.pub dest=/home/
      when: "{{ inventory_hostname == '192.168.6.142' }}"      
 #  - name: copy this file
 #    copy:
 #     src: /home/tim/sshkeys/sshkeytim.pub
 #     dest: /home/key1.pub
 #     remote_src: yes
 # - name: Ansible find examples
 #   command: "ls -l /home"
