---
- hosts: 192.168.6.145
  tasks:
   - name: copy this file
     copy:
      src: /home/tim/sshkeys/sshkeytim.pub
      dest: muddy@192.168.6.142:/home/key1.pub
      remote_src: yes
#  - name: Ansible find examples
#    command: "ls -l /home"
