---
- hosts: 127.0.0.1
  connection: local
  tasks:
 #  - name: copy this file
 #    copy:
 #     src: /home/tim/sshkeys/sshkeytim.pub
 #     dest: /home/key1.pub
 #     remote_src: yes
  - name: Ansible find examples
    command: "ls -l /home"
