---
- hosts: 192.168.6.142
  tasks:
  - name: Ansible find file examples
    find:
      paths: /home/
      age: 1d
#      register: files_matched
#
#  - debug:
#      msg: "{{ files_matched.files }}"
#    - name: copyfile
#      copy:
#        src: /home/muddy/file.txt
#        dest: /home/mudassar/file.txt
