#Nginx Removal
---
- hosts: testbox
  tasks:

    - name: stop nginx
      service:
       name: nginx
       state: stopped
    
    - name: uninstall nginx
      apt:
        name: nginx
        state: absent